version: '3.8'

services:
  # app:
  #   build: .
  #   environment:
  #     - ENV=development
  #   ports:
  #     - "5000:5000"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Porta do broker
      - "15672:15672"  # UI do RabbitMQ

  db:
    image: postgres
    container_name: postgress
    restart: always
    environment:
        POSTGRES_DB: curso_python
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
    ports:
    - "5433:5432"